spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      default_batch_fetch_size: 1000
    properties:
      hibernate:
      format_sql: true
      show_sql: true
    defer-datasource-initialization: true
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 2000
  sql:
    init:
      mode: always
      data-locations: classpath:h2/data.sql

logging:
  level:
    org.hibernate.sql: debug
