spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/board
    username: crudboard
    password: 0000
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      default_batch_fetch_size: 1000
    properties:
      hibernate:
      format_sql: true
      show_sql: true
  data:
    web:
      pageable:
        default-page-size: 5
        max-page-size: 2000

logging:
  level:
    org.hibernate.sql: debug
